#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

set +e

GLOBAL_STATUS=0

checkAndFormat() {
    local checkCommand="$1"
    local formatCommand="$2"
    nx $checkCommand >.husky/pre-commit.log 2>&1
    if [[ $? -eq 1 ]] ; then
        echo "Incorrectly formatted files found."
        nx $formatCommand >.husky/pre-commit.log
        echo "Executed the command: nx $formatCommand"
        GLOBAL_STATUS=1
    fi
}

checkAndFormat "format:check --uncommitted" "format:write --uncommitted"

exit $GLOBAL_STATUS
